name: Run
on:
  workflow_dispatch:
  schedule:
    - cron:  '0,30 * * * *'
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v2.4.0
      - name: 📥 Install
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: 🏃 Run
        env:
          COMMAND_CHANNEL_ID: ${{ secrets.COMMAND_CHANNEL_ID }}
          COMMAND_GUILD_ID: ${{ secrets.COMMAND_GUILD_ID }}
          TARGET_FRESHMEN_GUILD_ID: ${{ secrets.TARGET_FRESHMEN_GUILD_ID }}
          LOG_CHANNEL_ID: ${{ secrets.LOG_CHANNEL_ID }}
          TOKEN: ${{ secrets.TOKEN }}
          LOG_WEBHOOK: ${{ secrets.LOG_WEBHOOK }}
        run: echo hi # dotnet fsi Bot.fsx
      - uses: gautamkrishnar/keepalive-workflow@master # prevent GitHub from suspending this action due to repository inactivity
